version: '3'
services:
  telegram-bot:
    image: immorta192/miniapp:latest  # Убедитесь, что вы используете актуальный тег
    container_name: miniapp
    restart: always
    ports:
      - "80:80"  # Если нужно открыть порты
    environment:
      - TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}  # Укажите переменную окружения для токенаa
