version: '3'
services:
  telegram-bot:
    image: immorta192/miniapp
    container_name: miniapp
    restart: always
    ports:
      - "80:80"  # Если тебе нужно открыть какие-то порты
    environment:
      - YOUR_ENV_VARIABLE=value
