name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория,kek
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Установка Docker
      - name: Set up Docker
        run: |
          sudo apt-get update

        #Отладка SSH ключа
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
         ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

        
        #Тест SSH подключения
      - name: Test SSH connection
        run: |
               ssh -i ${{ secrets.SERVER_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo SSH connection successful"

      
      
      # 3. Подключение к серверу через SSH и деплой
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd MiniApp
            git pull origin main
            docker-compose down
            docker-compose up -d --build
