name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3. Удаление старых ключей из known_hosts
      - name: Clear known_hosts
        run: ssh-keygen -R "${{ secrets.SERVER_IP }}"
      
      
      
      # 2. Настройка SSH агента и добавление ключа.
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

        #Логирование
      - name: Debug SSH connection
        run: ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo SSH connection successful"



      # 4. Добавление сервера в known_hosts
      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # 5. Подключение по SSH и деплой
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd MiniApp
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
